spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://jeong-db.cj8uk6ey8mpd.ap-northeast-2.rds.amazonaws.com:5432/jeong
    username: jeong
    password: jeong123456789
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  data:
    redis:
      host: localhost
      port: 6379 # 추후에 AWS에 올려야 함, Redis 없는 사람들은 도커에 올려서 로컬로 돌려야 함!

  # cloud는 깃헙이 푸쉬가 하도 거절 당해서 안넣었습니다.

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

kakao:
  client_id: e1b5e97fb0b8676866a91d4957189312
  redirect_uri: http://localhost:8080/login/callback
  token_uri: https://kauth.kakao.com/oauth/token
  user_info_uri: https://kapi.kakao.com/v2/user/me

jwt:
  secret: '268fb4fcd7f4bc7c0dc1413f7202bb9f46293ca72f42ef4f0751a480e390c348' #HS256 알고리즘 사용
  access-token-validity-in-seconds: 1800 # 30분
  refresh-token-validity-in-seconds: 604800 # 7일

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.jeongchongmu.backend: DEBUG

file:
  upload-dir: uploads/

server:
  imageBaseUrl: http://localhost:8080/picture/

clova:
  api:
    url: https://7pbtfqu7ma.apigw.ntruss.com/custom/v1/43846/9f8859297c3b197d3487f9e1f14d6fe8930187f8ba70b889a386056388980128/document/receipt
    secret: R3pQYUFaa1lzY1JLTnlJZXJNcUZ4aGFNZnVqZWtaWGg=